# Generated by Django 2.0.2 on 2018-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=128)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("imdb_id", models.CharField(max_length=32)),
                ("release_year", models.CharField(max_length=4)),
                ("runtime", models.PositiveIntegerField()),
                ("story", models.TextField()),
                ("genres", models.ManyToManyField(to="core.Genre")),
            ],
        ),
        migrations.CreateModel(
            name="MoviePerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.ForeignKey(on_delete="PROTECT", to="core.Job")),
                ("movie", models.ForeignKey(on_delete="PROTECT", to="core.Movie")),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("imdb_id", models.CharField(max_length=32)),
                ("birthday", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="movieperson",
            name="person",
            field=models.ForeignKey(on_delete="PROTECT", to="core.Person"),
        ),
        migrations.AddField(
            model_name="image",
            name="movie",
            field=models.ForeignKey(on_delete="PROTECT", to="core.Movie"),
        ),
    ]
